### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by AbrasiveBoar902** [plusls/oh-my-minecraft-client#11]
可以增加一个3向清岩浆助手，自动把岩浆桶扔掉替换空桶，或者自定义自动扔物品

**Comment by plusls** [comment]
这个tweakeroo好像有了？

**Comment by AbrasiveBoar902** [comment]
emm没找到，我发之前翻了一遍

**Comment by plusls** [comment]
哎我记得tw有自动补货的来着，不慌，可以先画个饼（如果 tw 本身自带但是工作异常我会把这个功能实现在 MasaGadget 里

**Comment by Hendrix-Shen** [comment]
自定义丢弃物品可以使用 [TweakMyClient](https://www.curseforge.com/minecraft/mc-mods/tweakmyclient) 的`featureAutoDrop`

**Comment by plusls** [comment]
好！那我继续鸽了

**Comment by Hendrix-Shen** [comment]
> 好！那我继续鸽了

喵喵喵（咕咕咕）~

**Comment by AbrasiveBoar902** [comment]
> 
> 
> 哎我记得tw有自动补货的来着，不慌，可以先画个饼（如果 tw 本身自带但是工作异常我会把这个功能实现在 MasaGadget 里

tw的自动补货从背包拿桶类物品好像会出错

**Comment by plusls** [comment]
> > 哎我记得tw有自动补货的来着，不慌，可以先画个饼（如果 tw 本身自带但是工作异常我会把这个功能实现在 MasaGadget 里
> 
> tw的自动补货从背包拿桶类物品好像会出错

那这个功能应该会加到 MasaGadget，但是 MasaGadget 正在准备重构，加个 GUI 什么的

所以 咕咕咕咕咕

**Comment by plusls** [comment]
这个功能 tweakeroo 修好了，所以关了
