### ISSUE TITLE
高亮不会消失的实体

### ISSUE THREAD

**Issue by plusls** [plusls/oh-my-minecraft-client#18]
比如拿着墨囊的僵尸，拿着蘑菇的小黑、、、

**Comment by AbrasiveBoar902** [comment]
似乎高亮会有严重卡顿

**Comment by plusls** [comment]
> 似乎高亮会有严重卡顿

不会吧 游商高亮都不卡

**Comment by AbrasiveBoar902** [comment]
> 
> 
> > 似乎高亮会有严重卡顿
> 
> 不会吧 游商高亮都不卡

反正我镜头朝向高亮的游商fps会降低）
顺便问一下，那个自动筛选区块的工具在哪

**Comment by plusls** [comment]
https://gist.github.com/plusls/0be7bb8a5f61dca536cd3f70d8c039e7

**Comment by AbrasiveBoar902** [comment]
> 
> 
> https://gist.github.com/plusls/0be7bb8a5f61dca536cd3f70d8c039e7

（gist㕛打不开了

**Comment by AbrasiveBoar902** [comment]
> 
> 
> https://gist.github.com/plusls/0be7bb8a5f61dca536cd3f70d8c039e7

这个怎么用

**Comment by plusls** [comment]
> > https://gist.github.com/plusls/0be7bb8a5f61dca536cd3f70d8c039e7
> 
> 这个怎么用
```
out_dir = 'newlls'
in_dir = 'llsbackup'
# 20*60*30=36000 20*60*60=72000
inhabited_time = 36000
process_num = 12
```
自己改成你的配置
