### ISSUE TITLE
自动切换鞘翅功能，落地前打开容器的话，胸甲会错位

### ISSUE THREAD

**Issue by RevenXXX-a** [plusls/oh-my-minecraft-client#27]
如果在飞行过程中打开容器，落地后
箱子：胸甲会与 容器内 第7格物品交换
投掷器：胸甲会与 容器内 第7格物品交换

熔炉：胸甲会与 物品栏 第4格物品交换
漏斗：胸甲会与 物品栏 第2格物品交换

如果胸甲已在上述位置，则胸甲变成鼠标抓起状态。

另外希望在起跳前主动装备鞘翅，未使用自动切换功能时，落地之后不会自动切换胸甲。

**Comment by plusls** [comment]
因为飞行中查看容器的情况比较少见，处于修复考虑我可能会在切换前把容器关了？

**Comment by plusls** [comment]
以及在未启用自动切换时，是不会影响游戏行为的（新版已经修了这个bug）
