### ISSUE TITLE
和optifine冲突

### ISSUE THREAD

**Issue by SunnySlopes** [plusls/oh-my-minecraft-client#30]
1.16的0.3.9更新后和optifine冲突，报错如下
[crash-2021-10-13_08.12.23-client.txt](https://github.com/plusls/oh-my-minecraft-client/files/7333778/crash-2021-10-13_08.12.23-client.txt)
已知0.3.8和1.17的0.3.9没问题

**Comment by plusls** [comment]
啊我给opt的兼容代码在1.16没有测试过，毕竟opt是闭源代码，我回头看看

**Comment by plusls** [comment]
再下载一次试试？（上传了新的
