### ISSUE TITLE
一键整理有虫

### ISSUE THREAD

**Issue by acaciachan** [plusls/oh-my-minecraft-client#35]
手里拿着物品的时候，使用一键整理可能会导致手里的物品落到背包而不是箱子里。
有的时候，整理物品之后也会导致手上拿着一叠不满一组的额外物品
建议整理结束后发包检测一下手上有没有拿着物品，有的话放回箱子里之类的，也检测一下所选容器整理的是否正确。(可能是由网络延时引起的奇奇怪怪的问题)

**Comment by plusls** [comment]
emmm 先放到包里是故意写的，不是 bug，因为有的人说不定不想放箱子呢？（然而不想加太多可配置项）

手上拿着物品的话一般是客户端服务端不同步的问题？（或者是原来有物品你包满了塞不进去？）

**Comment by acaciachan** [comment]
啊，要不做成如果鼠标还是在箱子里的话那就放回箱子之类的，具体依据鼠标的位置上判定

**Comment by plusls** [comment]
这个可以有，很有道理（

**Comment by acaciachan** [comment]
不过这样做的话，那这个物品是停留在鼠标所在的格子呢还是shift键移动到这个容器里的结果，还是漏斗输入的结果呢？个人更倾向于shift移动，不然放的到处都是

**Comment by plusls** [comment]
> 不过这样做的话，那这个物品是停留在鼠标所在的格子呢还是shift键移动到这个容器里的结果，还是漏斗输入的结果呢？个人更倾向于shift移动，不然放的到处都是

和放进背包的行为一致，优先合并，然后再塞（但是怎么放都无所谓啊，你鼠标位置就决定了整理位置，反正都要整理的

**Comment by acaciachan** [comment]
那可以，对了整理的话能不能加一个音效啊，比如原版点击按钮出现的那个声音就可以

**Comment by plusls** [comment]
> 那可以，对了整理的话能不能加一个音效啊，比如原版点击按钮出现的那个声音就可以

有音效啊，每次按r都会有（不过有打算改成触发的时候才会响

**Comment by acaciachan** [comment]
啊是我的锅，F3+T重载资源包之后就能听到了

**Comment by acaciachan** [comment]
![image](https://user-images.githubusercontent.com/73088428/137712201-4e533bf0-00b4-4a57-947e-5bcce11c384e.png)
啊又发现了新的问题，就是你看图片这是一次整理之后的结果，不知道为什么需要整理第二遍才能让第二个格子的物品到最后

**Comment by plusls** [comment]
好（记一下

**Comment by acaciachan** [comment]
![image](https://user-images.githubusercontent.com/73088428/137712610-bcafa228-f6c3-49c1-a8a5-4dc17f63a8dc.png)
lkw另外有些nbt不同的潜影盒或者颜色不行的潜影盒也能否处理一下排在首或尾

**Comment by plusls** [comment]
> ![image](https://user-images.githubusercontent.com/73088428/137712610-bcafa228-f6c3-49c1-a8a5-4dc17f63a8dc.png) lkw另外有些nbt不同的潜影盒或者颜色不行的潜影盒也能否处理一下排在首或尾

有没有具体一点的方案？

**Comment by acaciachan** [comment]
emm，颜色的话可以参考创造模式的物品栏排列之类的？

**Comment by plusls** [comment]
啊我的意思是，优先考虑颜色，再考虑nbt还是啥

**Comment by acaciachan** [comment]
不过说实话创造模式的排列也挺那啥的，mojang一开始的16色颜色排序就很奥利给

**Comment by acaciachan** [comment]
优先考虑颜色，再nbt

**Comment by acaciachan** [comment]
因为nbt不同的话，还是同一物品

**Comment by plusls** [comment]
好（最近没空先咕，等忙完继续更

**Comment by plusls** [comment]
今晚看看能不能把排序功能重写了，用 swap 来进行交换，既能保证手中的物品不会被丢掉，还能降低发包次数
