### ISSUE TITLE
[新功能] 使用不死图腾后自动补充

### ISSUE THREAD

**Issue by SkyNetX007** [plusls/oh-my-minecraft-client#38]
能否加入新的功能：玩家触发图腾效果后，若背包有多余的图腾，能够自动补充到副手？

有时候长时间挂绿宝石 RAID ，服务器 TPS 可能不稳定，有时候需要用图腾续命，但是 tweakeroo 的自动补货似乎不支持图腾。

**Comment by plusls** [comment]
emm 这个问题我得确认一下 tw 能不能补，如果不能的话还得确认一下为什么不能补，并直接个 tw 发 pr
