### ISSUE TITLE
Feature Request: Highlight mobs preventing sleeping

### ISSUE THREAD

**Issue by Boobies** [plusls/oh-my-minecraft-client#39]
Could you implement the functionality of the mod called Monsters in the Closet? It makes mob glow when you click on a bed and they prevent sleeping. Monsters in the Closet has not been updated for 1.18.

**Comment by plusls** [comment]
I found that https://github.com/Minenash/MonstersInTheCloset/pull/5
it will have 1.18 version, and i will close this issue.
