### ISSUE TITLE
This mod and sodium used together crash with Quilt Loader

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [plusls/oh-my-minecraft-client#42]
**Describe the bug**
Fabric mods are supposed to work with the Quilt loader, but some do not for various reasons, most commonly relying on certain fabric internals. Quilt officially became beta yesterday, so I am reporting it now.

**To Reproduce**
1. Install the Quilt loader: https://quiltmc.org/install/
2. Download this mod.
3. Download malilib. https://www.curseforge.com/minecraft/mc-mods/malilib/files
4. Download the sodium mod. https://modrinth.com/mod/sodium/versions
5. Download quilt standard libraries. These are basically "quilt api", and bundle a "quilted fabric api" which replaces the normal "fabric api". https://modrinth.com/mod/qsl/versions
6. Try to launch the game
7. Notice that the game crashes on startup.

**Expected behavior**
I expected the mod to launch and work like it does on Fabric. Note that this only occurs with both ommc *and* sodium, when they are used individually no crash occurs.

**Desktop:**
 - Minecraft version [1.18.2]
 - Ommc version [0.4.2]
 - Sodium version [0.4.1]

**Minecraft crash report**
The game crashes before a crash report is generated. Here is [the log](https://gist.github.com/DragonEggBedrockBreaking/1b7dad4bc28c0e959f8bd42910634117).

**Comment by DragonEggBedrockBreaking** [comment]
I copy-pasted this from another bug report like this, editing the details to match the mod. That mod's issue reports require a specific format, which is why this report is formatted like this.

**Comment by wafflecoffee** [comment]
[Fake FLoader](https://modrinth.com/mod/fake-floader) should fix this

**Comment by plusls** [comment]
fixed
