### ISSUE TITLE
[BUG] Mixin崩溃

### ISSUE THREAD

**Issue by Phoupraw** [plusls/oh-my-minecraft-client#45]
启动器：HMCL
MC：1.18.2
OMMC：1.18.2-0.4.2
[crash-2022-05-19_11.46.01-client.txt](https://github.com/plusls/oh-my-minecraft-client/files/8723277/crash-2022-05-19_11.46.01-client.txt)
~~可能与[Xaero Map Addition](https://github.com/plusls/xaero-map-addition)和[MagicLib](https://github.com/Hendrix-Shen/MagicLib)有关。~~ 记忆中，我装上这两个模组后就开始崩溃了，但是现在我把这两个模组去掉仍然崩溃，把OMMC去掉才不崩溃。

**Comment by plusls** [comment]
建议上传一下mods文件夹

**Comment by Phoupraw** [comment]
> 建议上传一下mods文件夹

Cubist Texture-0.6.1.jar
itemscroller-fabric-1.18.2-0.16.0.jar
tweakermore-mc1.18.2-v3.2.0.jar
tweakeroo-fabric-1.18.2-0.13.3.jar
whats-that-slot-fabric-1.2.3+1.18.1.jar
【60+BUG修复】debugify-1.9.0-fabric-1.18.2.jar
【Architectury】architectury-4.3.53.jar
【ARRP】arrp-0.5.7.jar
【Cloth Config】cloth-config-6.2.57-fabric.jar
【Fabric API】fabric-api-0.51.1+1.18.2.jar
【Kotlin】fabric-language-kotlin-1.7.0+kotlin.1.6.0.jar
【masa前置】malilib-fabric-1.18.2-0.12.1.jar
【Reese的钠视频界面】reeses_sodium_options-mc1.18.2-1.4.2.jar
【REI】RoughlyEnoughItems-8.1.457.jar
【Textile备份】textile_backup-2.3.0-1.18.jar
【Xaero世界地图】XaerosWorldMap_1.21.2_Fabric_1.18.2.jar
【Xaero小地图】Xaeros_Minimap_22.7.0_Fabric_1.18.2.jar
【农夫乐事】farmers-delight-fabric-0.2.1.jar
【冰山】Iceberg-1.18.2-fabric-1.0.38.jar
【创世神CUI】WorldEditCUI-1.18.2+02-SNAPSHOT.jar
【创世神】worldedit-mod-7.2.10.jar
【合理排序】reasonable-sorting-1.5-mc1.18.2.jar
【地毯】fabric-carpet-1.18.2-pre3-1.4.65+v220223.jar
【增强视觉效果 前置】CreativeCore_FABRIC_v2.6.10_mc1.18.2.jar
【增强视觉效果】EnhancedVisuals_FABRIC_v1.5.4_mc1.18.2.jar
【彗星端】meteor-client-0.4.8.jar
【手持物品信息】held-item-info-1.2.0.jar
【按键增强】amecs-1.3.7+mc.1.18.2.jar
【旅行者标题 前置】YungsApi-1.18.2-Fabric-2.0.8.jar
【旅行者标题】TravelersTitles-1.18.2-Fabric-2.1.1.jar
【更好的任务栏】bettertaskbar-fabric-1.18.2-1.3.jar
【更好的潜行】BetterSneak-Fabric-1.18.2-1.0.0.jar
【木棍工作站】onastick-fabric-2.0.0.jar
【机械动力】create-mc1.18.2_v0.4.1+565.jar
【机械动力附加】createplus-1.0.0-beta4.jar
【树叶渲染优化】cullleaves-2.3.2.jar
【模组菜单】modmenu-3.2.1.jar
【滴落声】DripSounds-1.18-0.3.0.jar
【点击穿透】clickthrough-1.18.2-fabric0.47.10-0.4.jar
【物品边框】ItemBorders-1.18-fabric-1.1.5.jar
【物品高亮】Highlighter-1.18-fabric-1.1.2.jar
【界面背景模糊】blur-2.4.1.jar
【粒子雨】particle-rain-2.0.0.jar
【迷你HUD】minihud-fabric-1.18.2-0.22.0.jar
【钠 · 扩展】sodium-extra-mc1.18.2-0.4.3.jar
【钠】sodium-fabric-mc1.18.2-0.4.1+build.15.jar
【铟】indium-1.0.2+mc1.18.2.jar
【锂】lithium-fabric-mc1.18.2-0.7.9.jar

**Comment by yeetus-maximus** [comment]
i encounter same issues when OMMC is added to mods folder

**Comment by plusls** [comment]
新版的ommc也这样嘛

**Comment by yeetus-maximus** [comment]
yes the latest version of OMMC crashes with a message about terrain batching

**Comment by yeetus-maximus** [comment]
[crash-2022-06-04_12.45.40-client.txt](https://github.com/plusls/oh-my-minecraft-client/files/8867503/crash-2022-06-04_12.45.40-client.txt)

**Comment by plusls** [comment]
> [crash-2022-06-04_12.45.40-client.txt](https://github.com/plusls/oh-my-minecraft-client/files/8867503/crash-2022-06-04_12.45.40-client.txt)

I means use github action's version

**Comment by yeetus-maximus** [comment]
it works now but what was the issue anyways

**Comment by plusls** [comment]
> it works now but what was the issue anyways

because new fabric api update its render code, I compat it in new version

**Comment by yeetus-maximus** [comment]
`  "depends": {
    "magiclib": ">=0.5.25"`


huhhh?

**Comment by plusls** [comment]
https://github.com/Hendrix-Shen/MagicLib/releases/tag/dev%2F0.5.28

**Comment by IF-desu** [comment]
So I wonder how to download the latest verion ommc for 1.18.2now,I cant find it in Action

**Comment by IF-desu** [comment]
刚试了下1193的ommc（action里面的）和最新的magiclib，没加meteor时候可以进，不加进不去
[crash-2023-01-21_16.03.23-client.txt](https://github.com/plusls/oh-my-minecraft-client/files/10471762/crash-2023-01-21_16.03.23-client.txt)
