### ISSUE TITLE
ommc for 1.17.1 无法在最新的magiclib稳定构建上运行

### ISSUE THREAD

**Issue by Error-106** [plusls/oh-my-minecraft-client#74]
[错误报告-2023-3-24_18.51.06.zip](https://github.com/plusls/oh-my-minecraft-client/files/11061278/-2023-3-24_18.51.06.zip)

**Comment by Error-106** [comment]
测试环境：
	- fabric 0.46.1+1.17
	- fabricloader 0.14.18
	- java 17
	- malilib 0.10.0-dev.26
	- minecraft 1.17.1
	- ommc 0.5
magiclib-0.5.34正常运行
magiclib 0.7.293+17aa28c-stable发生崩溃

**Comment by Hendrix-Shen** [comment]
尝试此版本 [0.5.269+957c0dd](https://github.com/Nyan-Work/oh-my-minecraft-client/releases/tag/nyan-work%2Fdev.12)。
