### ISSUE TITLE
[建议] 在模组菜单内添加设置按钮

### ISSUE THREAD

**Issue by Phoupraw** [plusls/oh-my-minecraft-client#76]
由于模组设置快捷键经常失效，所以建议提供另一个访问设置的方法。

**Comment by Hendrix-Shen** [comment]
OMMC本身有 Mod Menu 的配置按钮，若不显示说明模组未成功加载。

**Comment by Phoupraw** [comment]
~~OMMC为什么会显示在模组菜单的列表中但是又未成功加载？~~
> Mod ommc provides a broken implementation of ModMenuApi

[latest.log](https://github.com/plusls/oh-my-minecraft-client/files/11224639/latest.log)

**Comment by Hendrix-Shen** [comment]
请到 [此处](https://github.com/Nyan-Work/oh-my-minecraft-client/releases) 升级 OMMC。

**Comment by Phoupraw** [comment]
将OMMC升级到1.19.2-0.5.273+40a44e1-beta、将MagicLib升级到0.7.302+8d1be4b-beta后解决此问题。
