### ISSUE TITLE
启动游戏时崩溃

### ISSUE THREAD

**Issue by Phoupraw** [plusls/oh-my-minecraft-client#81]
[minecraft-exported-crash-info-2023-07-25T20-27-02.zip](https://github.com/plusls/oh-my-minecraft-client/files/12161020/minecraft-exported-crash-info-2023-07-25T20-27-02.zip)

**Comment by Phoupraw** [comment]
改用v0.5后不再崩溃，但是无法打开配置界面。
[latest.log](https://github.com/plusls/oh-my-minecraft-client/files/12161124/latest.log)

**Comment by liqwang** [comment]
0.5版本只支持到1.19：https://modrinth.com/mod/oh-my-minecraft-client/version/0.5
项目目前在这个仓库维护，里面的beta版支持到了1.20.1
https://github.com/Nyan-Work/oh-my-minecraft-client/releases

**Comment by Phoupraw** [comment]
我当前在用`1.20.1-0.5.304+a200fcc-beta`，正常使用。
